[package]
name = "hooke"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name="hooke"
path="src/lib.rs"

[dependencies]
rust-stemmers="*"
stop-words="*"
regex="*"
